version: 1

formatters:
  simple:
    format: "%(asctime)s - %(threadName)s - %(name)s:%(lineno)d - %(levelname)s - %(funcName)s - %(message)s"

handlers:
  file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/celery.log
    when: midnight
    interval: 1
    backupCount: 7
    encoding: utf8

loggers:
  consumer:
    level: WARNING
    handlers: [file_handler]
    propagate: no

  scheduler:
    level: WARNING
    handlers: [file_handler]
    propagate: no

  apscheduler: # for trouble shooting
    level: WARNING
    handlers: [file_handler]
    propagate: no

  celery:
    level: DEBUG
    handlers: [file_handler]
    propagate: no

root:
  level: INFO
  handlers: [file_handler]
